### ISSUE TITLE
How to use in Unity3D?

### ISSUE THREAD

**Issue by orangeagain** [KuraiAndras/Injecter#68]
Is this library to instead of "Microsoft.Extensions.DependencyInjection" on Unity3D?

**Comment by orangeagain** [comment]
import release unitypackage, give  error:`The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft'`

**Comment by KuraiAndras** [comment]
Yes, the package has some dependencies as stated by the [documentation](https://kuraiandras.github.io/Injecter/documentation/injecter.unity.html). You have a couple of options for getting the NuGet packages
- [UnityNuGet](https://github.com/xoofx/UnityNuGet) (this right now does not have Injecter, but i will make a pull request soon)
- [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity)
- Download the DLLs manually from [NuGet.org](https://www.nuget.org/). Download the nuget packages, unzip them, and copy the dlls from the netstandard2.0 folders
- A combination of the above

Also it is advised that you use the [upm](https://openupm.com/packages/com.injecter.unity/) version of Injecter.Unity, the .unitypackage releases are no longer published

After you are set up, follow the [documentation](https://kuraiandras.github.io/Injecter/documentation/injecter.unity.html)

Edit:
[PR](https://github.com/xoofx/UnityNuGet/pull/53) on the UnityNuGet repo.

**Comment by orangeagain** [comment]
Thank for you reply,this sitution is I want to use uploder library [BirdMessenger ](https://github.com/bluetianx/BirdMessenger)in unity,
so I add [Microsoft.Extensions.Hosting.Unity](https://github.com/amelkor/Microsoft.Extensions.Hosting.Unity) and [Injecter](https://github.com/KuraiAndras/Injecter) to unity project, 
report error:` 'IServiceCollection' does not contain a definition for 'AddHttpClient' and no accessible extension method 'AddHttpClient' accepting a first argument of type 'IServiceCollection' could be found `
finally,I give up this solution.and use httpclient to implement upload function.

**Comment by KuraiAndras** [comment]
Well, library you linked is not mine. But I also have [package](https://openupm.com/packages/com.injecter.hosting.unity/) which adds Hosting support. [docs](https://kuraiandras.github.io/Injecter/documentation/injecter.hosting.unity.html).

Also, you get that error message because you did not install [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http) nuget package

**Comment by orangeagain** [comment]
> Well, library you linked is not mine. But I also have [package](https://openupm.com/packages/com.injecter.hosting.unity/) which adds Hosting support. [docs](https://kuraiandras.github.io/Injecter/documentation/injecter.hosting.unity.html).
> 
> Also, you get that error message because you did not install [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http) nuget package

thank you,finally I download nuget Microsoft.Extensions.Hosting dll to unity resolve rely porblem.
