### ISSUE TITLE
Package manager installation does not work 

### ISSUE THREAD

**Issue by NicolasAvatar** [KuraiAndras/Injecter#96]
Thanks for sharing your DI plugin for Unity, just wanted to share that https://openupm.com/packages/com.injecter.unity/?subPage=related#modal-manualinstallation does not work:

![image](https://user-images.githubusercontent.com/99667494/174593153-0176f986-7e7f-4509-908a-8bd4cc3337c1.png)

**Comment by KuraiAndras** [comment]
That is because the user has to provide the necessary dependencies. You must install the Microsoft.Extensions.Hosting and related packages. The easiest way is through https://github.com/xoofx/UnityNuGet/g

**Comment by NicolasAvatar** [comment]
Thanks for your quick reply, I am eventually using your https://openupm.com/packages/com.extenject.microsoft/?subPage=readme which is working like a charm with Extenject
